export interface PhoneColor {
  name: string
  hex: string
}

export const PHONE_COLORS: PhoneColor[] = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Gray", hex: "#808080" },
  { name: "Space Gray", hex: "#4A4A4A" },
  { name: "Slate", hex: "#5C5C5C" },
  { name: "Graphite", hex: "#3B3B3B" },
  { name: "Natural Titanium", hex: "#D4D0C8" },
  { name: "Black Titanium", hex: "#1C1C1E" },
  { name: "White Titanium", hex: "#E8E8E8" },
  { name: "Gold", hex: "#F5D6A8" },
  { name: "Rose Gold", hex: "#E8B4B8" },
  { name: "Yellow Gold", hex: "#D4AF37" },
  { name: "Desert Titanium", hex: "#C4A882" },
  { name: "Blue", hex: "#2196F3" },
  { name: "Blue Titanium", hex: "#4A6FA5" },
  { name: "Pacific Blue", hex: "#1D5B79" },
  { name: "Sierra Blue", hex: "#A0C4D6" },
  { name: "Alpine Blue", hex: "#5F7D9E" },
  { name: "Deep Blue", hex: "#0D47A1" },
  { name: "Teal", hex: "#008080" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Green", hex: "#4CAF50" },
  { name: "Midnight Green", hex: "#2E5B4C" },
  { name: "Alpine Green", hex: "#4A7C6F" },
  { name: "Mint Green", hex: "#98FB98" },
  { name: "Purple", hex: "#800080" },
  { name: "Deep Purple", hex: "#5E4DB2" },
  { name: "Lavender", hex: "#B39DDB" },
  { name: "Red", hex: "#D32F2F" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Pink", hex: "#FF69B4" },
  { name: "Rose Pink", hex: "#FF66B2" },
  { name: "Yellow", hex: "#FFD700" },
  { name: "Orange", hex: "#FF9800" },
  { name: "Peach", hex: "#FFDAB9" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Starlight", hex: "#F8F6F0" },
  { name: "Midnight", hex: "#1C1C1E" },
  { name: "Jet Black", hex: "#0A0A0A" },
  { name: "Space Black", hex: "#2C2C2E" },
]
